# Bateery section
SENSOR_NAME_BATTERY_PERCENT = 'Battery' # %
SENSOR_NAME_BATTERY_POWER_PLUGGED = 'Power Plugged' # 0: Unplugged, 1: Plugged
SENSOR_NAME_BATTERY_LEFT = 'Battery Left' # Hours

# CPUs section  
SENSOR_NAME_CPU_USAGE = 'CPU Uasege' # %

# Disks section
SENSOR_NAME_DISKS_SPACE = 'Disk Space {}'
SENSOR_NAME_DISKS_TOTAL_SPACE = 'Total' # MB
SENSOR_NAME_DISKS_USED_SPACE = 'Used' # MB
SENSOR_NAME_DISKS_FREE_SPACE = 'Free' # MB
SENSOR_NAME_DISKS_PERCENT_USED = 'Disk Usage'

# Memory section
DEVICE_NAME_MEMORY_VIRTUAL = 'Memory '
DEVICE_NAME_MEMORY_SWAP = 'Swap '
SENSOR_NAME_MEMORY_SPACE = 'Space'
SENSOR_NAME_MEMORY_PERCENT = 'Usage'

# Fans section
SENSOR_NAME_FANS = 'Fans'
SENSOR_NAME_FANS_FORMAT =  '{} {}' # RPM

# Network section
SENSOR_NAME_NETWORKS = 'Network {}'
SENSOR_NAME_NETWORKS_PACKET = 'Packets'
SENSOR_NAME_NETWORKS_BANDWIDTH = 'Bandwidth'
SENSOR_NAME_NETWORKS_SENT = 'Sent' # MB
SENSOR_NAME_NETWORKS_RECV = 'Recieved' # MB

# Temperature section
SENSOR_NAME_TEMPERATURE_NAME = 'Temperature {} {}'
SENSOR_NAME_TEMPERATURE_CURRENT = 'Current'
SENSOR_NAME_TEMPERATURE_HIGH = 'High'
SENSOR_NAME_TEMPERATURE_CRITICAL = 'Critical'

# General Sensor Names
SENSOR_NAME_TEMPERATURE = 'Temperature'
SENSOR_NAME_HUMIDITY = 'Humidity'
SENSOR_NAME_LIGHT = 'Light'
SENSOR_NAME_SOUND = 'Sound'
SENSOR_NAME_STATUS = 'Status'
SENSOR_NAME_PRESSURE = 'Pressure'
SENSOR_NAME_SMOKE = 'Smoke'
SENSOR_NAME_SERVER = 'LocalServer'
SENSOR_NAME_DOORLOCK = 'DoorLock'